###
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
    "email": "ee@gmail.com",
    "password": "12344",
    "name": "ee"
}

###
POST http://localhost:8080/auth/signin
Content-Type: application/json

{
    "email": "ee@gmail.com",
    "password": "newPass"
}

###
POST http://localhost:8080/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": 
        "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OWM1MzBlY2EyMDM1MGJlYjIzZmY0MDIiLCJpYXQiOjE3NzQ2OTYzNTYsImV4cCI6MTc3NDc4Mjc1Nn0.g7yryQFHU2zu_OqD69BZIp2gfxny0a3nw4j0BHUvsJU"
}

###
POST http://localhost:8080/auth/logout
Content-Type: application/json

###
PATCH http://localhost:8080/userManagement/ee@gmail.com/password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OWM1MzBlY2EyMDM1MGJlYjIzZmY0MDIiLCJpYXQiOjE3NzQ2OTY1MDMsImV4cCI6MTc3NDcwMDEwM30.66-GbFdsF8ljjB4JVmVriOkCeq-OMxhofODfvI6pS8Q

{
    "newPassword": "newPass2",
    "oldPassword": "newPass"
}

###
GET http://localhost:8080/userManagement/ee@gmail.com/account
Content-Type: application/json

###
GET http://localhost:8080/userManagement/ee@gmail.com/preferences
Content-Type: application/json